# Generated by Django 4.2.11 on 2024-04-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_technician_service_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10, verbose_name='Қызмет ақысы'),
        ),
    ]
